spring.application.name=customer-handler

spring.profiles.active=dev

crm.welcome-message=Hello Dunyaa!!
crm.maxResults=50


logging.level.root=INFO
logging.level.org.springframework.web=INFO

# Separate...
logging.level.org.blackbergx9.customerhandler=DEBUG
logging.level.org.blackbergx9.customerhandler.repository=DEBUG

# Grouping...
logging.group.crm-debug=org.blackbergx9.customerhandler, org.blackbergx9.customerhandler.repository
logging.level.crm-debug=debug
